- name: Install Docker
  hosts: localhost
  become: yes
  tasks:
    - name: Install Docker
      apt: 
        name: docker ce
        state: present
        update_cache: yes

    - name: Ensure Docker is running
      systemd: 
        name: docker
        state: started
        enabled: yes
        