- name: Install Docker
  hosts: localhost
  become: yes
  tasks:
    - name: Install required sysem packages
      apt:
        name: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common']
        state: present

    - name: Install Docker
      apt: 
        name: docker ce
        state: present
        update_cache: yes

    - name: Ensure Docker is running
      systemd: 
        name: docker
        state: started
        enabled: yes
        