- name: Build and Run Helloworld Docker Container
  hosts: localhost
  become: yes
  tasks:
    - name: Build Docker Image
      docker_image: 
        path: ./helloworld
        name: helloworld
        source: build

    - name: Run the Docker Container
      docker_container:
        name: helloworld
        image: helloworld
        state: started
        recreate: yes
        published_ports:
          - "8080":"8080"
